import { supabase } from "@/integrations/supabase/client";
import { CartItem } from "@/lib/constants";
import { getCookieIdHash, getUserAgent } from "@/lib/identitySignals";

interface OrderInput {
  customerName: string;
  customerPhone: string;
  city: string;
  region: string;
  addressLine1: string;
  isTbilisi: boolean;
  items: CartItem[];
  subtotal: number;
  total: number;
}

export async function createOrder(input: OrderInput) {
  const cookieIdHash = getCookieIdHash();
  const userAgent = getUserAgent();

  // Insert order — public_order_number is auto-generated by trigger when empty string
  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      customer_name: input.customerName,
      customer_phone: input.customerPhone,
      city: input.city,
      region: input.region,
      address_line1: input.addressLine1,
      is_tbilisi: input.isTbilisi,
      subtotal: input.subtotal,
      total: input.total,
      status: "new",
      payment_method: "COD",
      public_order_number: "",
      raw_city: input.city,
      raw_address: input.addressLine1,
      cookie_id_hash: cookieIdHash,
      user_agent: userAgent,
    } as any) // eslint-disable-line @typescript-eslint/no-explicit-any
    .select("id, public_order_number")
    .single();

  if (orderError) throw orderError;

  // Insert order items
  const itemRows = input.items.map((item) => ({
    order_id: order.id,
    product_id: item.product.id,
    sku: item.product.sku || item.product.id,
    title: item.product.title,
    quantity: item.quantity,
    unit_price: item.product.price,
    line_total: item.product.price * item.quantity,
    image_url: item.product.image || "",
  }));

  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(itemRows);

  if (itemsError) throw itemsError;

  // Create initial event
  await supabase.from("order_events").insert({
    order_id: order.id,
    actor: "system",
    event_type: "status_change",
    payload: { from: null, to: "new", source: "storefront_checkout" },
  });

  // Fire-and-forget: normalize and score
  try {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
    fetch(`${supabaseUrl}/functions/v1/normalize-and-score`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "apikey": supabaseKey,
        "Authorization": `Bearer ${supabaseKey}`,
      },
      body: JSON.stringify({ order_id: order.id }),
    });
  } catch (e) {
    console.warn("normalize-and-score call failed:", e);
  }

  return order;
}
