import { supabase } from "@/integrations/supabase/client";
import { CartItem, Product } from "@/lib/constants";
import { getCookieIdHash, getUserAgent } from "@/lib/identitySignals";
import { logSystemEvent, logSystemEventFailed } from "@/lib/systemEventService";

interface OrderInput {
  customerName: string;
  customerPhone: string;
  city?: string;
  region?: string;
  addressLine1?: string;
  isTbilisi?: boolean;
  items: CartItem[];
  subtotal: number;
  shippingFee?: number;
  total: number;
  source?: string;
  landingSlug?: string;
  status?: string;
}

/** Server-side OOS check: verify all items are in stock before creating order */
async function checkStockAvailability(items: CartItem[]): Promise<string[]> {
  const productIds = items.map((i) => i.product.id);
  
  const { data: overrides } = await supabase
    .from("product_stock_overrides")
    .select("product_id, available")
    .in("product_id", productIds);

  if (!overrides) return [];
  
  return overrides
    .filter((o) => o.available === false)
    .map((o) => {
      const item = items.find((i) => i.product.id === o.product_id);
      return item?.product.title || o.product_id;
    });
}

export async function createOrder(input: OrderInput) {
  const cookieIdHash = getCookieIdHash();
  const userAgent = getUserAgent();

  let orderId = "unknown";

  try {
    // SERVER-SIDE OOS CHECK: Block order if any item is out of stock
    const oosItems = await checkStockAvailability(input.items);
    if (oosItems.length > 0) {
      const error = new Error(`OUT_OF_STOCK: ${oosItems.join(", ")}`);
      (error as any).oosItems = oosItems;
      throw error;
    }

    // Insert order — public_order_number is auto-generated by trigger when empty string
    const orderSource = input.source || "lovable";
    const orderStatus = input.status || "new";
    const { data: order, error: orderError } = await supabase
      .from("orders")
      .insert({
        customer_name: input.customerName,
        customer_phone: input.customerPhone,
        city: input.city || "",
        region: input.region || "",
        address_line1: input.addressLine1 || "",
        is_tbilisi: input.isTbilisi ?? false,
        subtotal: input.subtotal,
        total: input.total,
        status: orderStatus,
        payment_method: "COD",
        public_order_number: "",
        raw_city: input.city || "",
        raw_address: input.addressLine1 || "",
        cookie_id_hash: cookieIdHash,
        user_agent: userAgent,
        source: orderSource,
        shipping_fee: input.shippingFee ?? 0,
        ...(input.landingSlug ? { tags: [`landing:${input.landingSlug}`] } : {}),
      } as any)
      .select("id, public_order_number")
      .single();

    if (orderError) throw orderError;
    orderId = order.id;

    // Insert order items
    const itemRows = input.items.map((item) => ({
      order_id: order.id,
      product_id: item.product.id,
      sku: item.product.sku || item.product.id,
      title: item.product.title,
      quantity: item.quantity,
      unit_price: item.product.price,
      line_total: item.product.price * item.quantity,
      image_url: item.product.image || "",
    }));

    const { error: itemsError } = await supabase
      .from("order_items")
      .insert(itemRows);

    if (itemsError) throw itemsError;

    // Create initial event
    await supabase.from("order_events").insert({
      order_id: order.id,
      actor: "system",
      event_type: "status_change",
      payload: { from: null, to: orderStatus, source: "storefront_checkout" },
    });

    // Log SUCCESS system event
    await logSystemEvent({
      entityType: "order",
      entityId: order.id,
      eventType: "ORDER_CREATE",
      actorId: "storefront",
      payload: {
        public_order_number: order.public_order_number,
        total: input.total,
        item_count: input.items.length,
      },
    });

    // Fire-and-forget: normalize and score (skip for pending_details)
    if (orderStatus !== "pending_details") {
      try {
        const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
        const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
        fetch(`${supabaseUrl}/functions/v1/normalize-and-score`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "apikey": supabaseKey,
            "Authorization": `Bearer ${supabaseKey}`,
          },
          body: JSON.stringify({ order_id: order.id }),
        });
      } catch (e) {
        console.warn("normalize-and-score call failed:", e);
      }
    }

    return order;
  } catch (err: any) {
    // Log FAILED system event
    await logSystemEventFailed({
      entityType: "order",
      entityId: orderId,
      eventType: "ORDER_CREATE",
      actorId: "storefront",
      errorMessage: err?.message || String(err),
      payload: { customer_phone: input.customerPhone, total: input.total },
    });
    throw err;
  }
}

/** Add upsell items to an existing order and update totals */
export async function addUpsellItems(
  orderId: string,
  items: { product: Product; quantity: number }[],
  newShippingFee: number,
  newTotal: number
) {
  // Insert additional order_items
  const itemRows = items.map((item) => ({
    order_id: orderId,
    product_id: item.product.id,
    sku: item.product.sku || item.product.id,
    title: item.product.title,
    quantity: item.quantity,
    unit_price: item.product.price,
    line_total: item.product.price * item.quantity,
    image_url: item.product.image || "",
    tags: ["upsell"],
  }));

  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(itemRows);

  if (itemsError) throw itemsError;

  // Update order totals
  const { error: updateError } = await supabase
    .from("orders")
    .update({
      shipping_fee: newShippingFee,
      total: newTotal,
      subtotal: newTotal - newShippingFee,
    } as any)
    .eq("id", orderId);

  if (updateError) throw updateError;
}

/** Update order with address details and finalize status.
 *  `addressStatus`: 'completed' when both city + address are present, 'partial' when only city. */
export async function updateOrderAddress(
  orderId: string,
  data: {
    city: string;
    region: string;
    addressLine1: string;
    isTbilisi: boolean;
    addressStatus?: "completed" | "partial";
  }
) {
  const status = data.addressStatus || (data.addressLine1.trim() ? "completed" : "partial");
  const { error } = await supabase
    .from("orders")
    .update({
      city: data.city,
      region: data.region,
      address_line1: data.addressLine1,
      raw_city: data.city,
      raw_address: data.addressLine1,
      is_tbilisi: data.isTbilisi,
      status: "new",
      address_status: status,
      address_added_at: new Date().toISOString(),
      skipped_address: false,
    } as any)
    .eq("id", orderId);

  if (error) throw error;

  try {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
    fetch(`${supabaseUrl}/functions/v1/normalize-and-score`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "apikey": supabaseKey,
        "Authorization": `Bearer ${supabaseKey}`,
      },
      body: JSON.stringify({ order_id: orderId }),
    });
  } catch (e) {
    console.warn("normalize-and-score call failed:", e);
  }
}

/** Mark that the customer explicitly skipped the address popup. Does not delete the order. */
export async function markOrderAddressSkipped(orderId: string) {
  const { error } = await supabase
    .from("orders")
    .update({
      skipped_address: true,
      address_status: "missing",
    } as any)
    .eq("id", orderId);
  if (error) throw error;
}

